name: "w3security code test"
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: w3security/actions/setup@master
      - name: W3Security Test
        run: w3security code test --org=${{ secrets.W3SECURITY_ORG }} --sarif > w3security-sarif2.json
        continue-on-error: true
        env:
           W3SECURITY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: w3security-sarif2.json
